visualization_program: "C:/Users/gnil/Python project/config_2/plantuml-gplv2-1.2024.8.jar"
repository_path: "C:/Users/gnil/niaspo/practice8/docker_maven"
output_image_path: "C:/Users/gnil/Python project/config_2/output.png"
commit_date: "2023-01-01"
